tareas_index:
  path:     '/'
  methods:  [GET]
  defaults: { _controller: WebManagementBundle:Tarea:index }

tareas_nueva_ajax:
  path:     '/nueva-ajax'
  methods:  [GET]
  defaults: { _controller: WebManagementBundle:Tarea:nuevaAjax }
