<?php

namespace WebManagementBundle\Repository;

use WebManagementBundle\Entity\Empresa;
use WebManagementBundle\Entity\Categoria;

/**
 * EmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Metodo que crea una empresa vacia y retorna el id
     * @param $entityManager
     * @return int
     */
    public function add($entityManager){

        $empresa = new Empresa();
        $empresa->setNombre('');
        $empresa->setProvincia('');
        $empresa->setPoblacion('');
        $empresa->setEmail('');
        $empresa->setActivo(true);
        $empresa->setPrioridad(1);
        $empresa->setFecha(new \DateTime);

        $entityManager->persist($empresa);
        $entityManager->flush();

        return $empresa->getId();
    }
}
